### PR TITLE
Fix nodeBuds paragraph alignment, turnback class

### LINKED ISSUE #49: Fix some CSS bugs in `why-join-nodebuds.svelte` section
Specifically, the text needs to be tweaked so that it is aligned properly in both mobile and desktop dimensions.

Here is the [file in question](https://github.com/EthanThatOneKid/acmcsuf.com/blob/main/src/components/sections/why-join-nodebuds.svelte). Happy bug-fixing 😊!

### PR DESCRIPTION
**Pull request by diamondburned**
Fix nodeBuds paragraph alignment, turnback class
    
    This commit fixes the second paragraph's alignment in mobile view to
    render properly. It also fixes a minor capitalization error ("nodebuds"
    to "nodeBuds").
    
    This commit also adds the groundwork for potential future refactoring:
    the CSS variables --fluid-font-size, --p-font-size and --h-font-size-med
    were introduced to slowly replace the previous fluidSize mixin.
    
    The --fluid-font-size uses the CSS clamp() math function to achieve
    smoothly scalable font sizes across all viewports unlike setting manual
    font-sizes over @media. This behavior is almost similar to the mixin.
    Its intended use case is to be set at the parent container (or the
    body). Note that this affects the margins and paddings if they use em as
    well.
    
    The two new font size variables, --p-font-size and --h-font-size-med,
    are in em units to properly utilize the above --fluid-font-size set in
    the parent container. The em units will scale accordingly. This is
    different from using px, which is scaled absolutely (as opposed to
    relatively to the parent's font-size).

---

This PR closes #49.

Certain note-worthy things:

1. The old `<div class="turnback">` that wraps everything is removed.
2. `<div class="turnback">` is only used to wrap the text paragraph now.
3. `.turnback` CSS code should be OK to be copy-pasted into `global.css` once other components remove its own (probably).

### CODE REVIEW

**Comment by diamondburned** [comment]
Relevant issue: https://github.com/EthanThatOneKid/acmcsuf.com/issues/13, also to do with the `fluidSize` mixin refactor.

File: src/components/sections/why-join-nodebuds.svelte [hunk 1]
```diff
@@ -1,82 +1,89 @@
...
+    #why-join-nodebuds > img {
+      width: max(55vw, 550px);
+      max-width: 100%;
+    }
+    #why-join-nodebuds > .turnback > p {
+      max-width: max(30vw, 300px);
+    }
+
+    .turnback,
+    .turnback:nth-child(even) {
```
Comment (EthanThatOneKid) [inline src/components/sections/why-join-nodebuds.svelte:82]: Here, the `.turnback:nth-child(even)` selector is possibly unnecessary since the `.turnback` selector should work for all `.turnback:nth-child(even)` elements.

**Review by EthanThatOneKid — COMMENTED** [review]
Overall these changes look great! I am looking forward to dropping in these utility classes from the `global.css` file.

Additionally, thank you for the very detailed commit message. It was a good read.

File: src/components/sections/why-join-nodebuds.svelte (hunk 1 above)
Comment (diamondburned) [reply src/components/sections/why-join-nodebuds.svelte:82]: I actually tested this, and without the `:nth-child(even)`, the outer one would take priority over this one.

Comment (EthanThatOneKid) [reply src/components/sections/why-join-nodebuds.svelte:82]: Ah that makes sense. Thank you for looking into that. 😀

That would align with CSS's concept of [_specificity_](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).
