### PR TITLE
Refactor copy function into its own folder + fix blog typo

### LINKED ISSUE #628: Blog: Regression introduced in copy code feature
### What happened?

In PR #621, a typo was introduced that shows some JavaScript code along with the markup.

### Screenshot

image

### Further refactoring

There might be a way to modularize the copy function. As suggested in: https://github.com/EthanThatOneKid/acmcsuf.com/pull/621#discussion_r998915070.

### PR DESCRIPTION
**Pull request by anhduy1202**
# Description
- I've refactored the copy function into its own folder ```lib/public/copy``` according to @EthanThatOneKid suggestion
- I've removed the gibberish typo on the blog

# Result
The copy feature works fine when I tested

### CODE REVIEW

**Review by jaasonw — CHANGES_REQUESTED** [review]
cant provide a more comprehensive review rn but
1. toast is missing border
2. copy doesnt work on events anymore
3. document the copy function

**Comment by anhduy1202** [comment]
> cant provide a more comprehensive review rn but
> 
> 1. toast is missing border
> 2. copy doesnt work on events anymore
> 3. document the copy function

Screen Shot 2022-10-22 at 8 34 56 PM

File: src/lib/public/copy/copy.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { toast, ToastType } from '$lib/components/toaster/toasts';
+
+export default function copy(
```
Comment (EthanThatOneKid) [inline src/lib/public/copy/copy.ts]: Nit: To remain consistent with the rest of the repository, we could export without the `default` keyword.
```suggestion
export function copy(
```

File: src/lib/public/copy/copy.ts [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+  link: string,
+  successMessage: string,
+  path: string,
+  errorMessage: string
```
Comment (EthanThatOneKid) [inline src/lib/public/copy/copy.ts]: The original `copy` function, featured in [src/routes/(site)/events/event.svelte](https://github.com/EthanThatOneKid/acmcsuf.com/blob/933fa16bad61ef85c224950614c6d67edaa9cf6b/src/routes/(site)/events/event.svelte#L17), contained these arguments in the order:
1. link: string
2. successMessage: string
3. errorMessage: string
4. path: string

Where `path` represents an identifier for a specific team name used by the `toast` function to determine a team-specific highlight color. Acknowledging #470, we can choose the name `teamId` over `path`.

```suggestion
  link: string,
  successMessage: string,
  errorMessage: string,
  teamId: string
```

File: src/routes/(site)/blog/[id]/+page.svelte [hunk 3]
```diff
@@ -6,7 +6,7 @@
   import Labels from '$lib/components/blog/labels.svelte';
   import BlogBody from './blog-body.svelte';
   import { onMount } from 'svelte';
```
Comment (EthanThatOneKid) [inline src/routes/(site)/blog/[id]/+page.svelte]: In the onMount function of this file, resolve any lint errors.
image

File: src/routes/(site)/blog/[id]/blog-body.svelte [hunk 4]
```diff
@@ -26,11 +26,11 @@
 >`;
     const svgCode = encodeURI(svg);
     for (let code of pre) {
-      let parentDiv = code.parentElement;
+      const parentDiv = code.parentElement;
       if (parentDiv) {
-        parentDiv!.style.position = 'relative';
+        parentDiv.style.position = 'relative';
```
Comment (EthanThatOneKid) [inline src/routes/(site)/blog/[id]/blog-body.svelte]: In CSS, we could write this out as...
```css
:global(div:has(pre)) {
  position: relative;
}
```

File: src/routes/(site)/blog/[id]/blog-body.svelte [hunk 5]
```diff
@@ -26,11 +26,11 @@
...
       }
-      let copyBtn = document.createElement('button');
+      const copyBtn = document.createElement('button');
       copyBtn.classList.add('copy-code');
       copyBtn.style.cssText =
         'position: absolute; padding: 1rem; top: 1rem; right: 1rem; outline: none; background-color: transparent; border:none; cursor: pointer';
```
Comment (EthanThatOneKid) [inline src/routes/(site)/blog/[id]/blog-body.svelte]: In CSS, we could write this out as...
```css
:global(.copy-code) {
  position: absolute;
  passing: 1rem;
  top: 1rem;
  right: 1rem;
  outline: none;
  background-color: transparent;
  border: none;
  cursor: pointer;
  background-image: url(/assets/svg/copy-text.svg);
}
```

Note: With respect to #623, the SVG used for the `.copy-code` button could come from the `/static` directory.

**Review by EthanThatOneKid — CHANGES_REQUESTED** [review]
I did not review the techniques used in #621 before it merged, so I left some comments on code written in that PR. Thank you for following up with this PR!

File: src/lib/public/copy/copy.ts (hunk 1 above)
Comment (anhduy1202) [reply src/lib/public/copy/copy.ts]: done

File: src/lib/public/copy/copy.ts (hunk 2 above)
Comment (anhduy1202) [reply src/lib/public/copy/copy.ts]: done

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 4 above)
Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: done

Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: actually I don't think CSS applies it since the style got applied during the for loop through DOM manipulation

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 5 above)
Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: done

File: src/routes/(site)/blog/[id]/+page.svelte (hunk 3 above)
Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/+page.svelte]: done

File: src/routes/(site)/blog/[id]/blog-body.svelte [hunk 6]
```diff
@@ -3,38 +3,13 @@
...
-    stroke-width="32"
-  /></svg
->`;
-    const svgCode = encodeURI(svg);
     for (let code of pre) {
-      let parentDiv = code.parentElement;
+      const parentDiv = code.parentElement;
       if (parentDiv) {
-        parentDiv!.style.position = 'relative';
+        parentDiv.style.position = 'relative';
```
Comment (EthanThatOneKid) [inline src/routes/(site)/blog/[id]/blog-body.svelte]: Nit: This style could be defined in the styles section.

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 4 above)
Comment (EthanThatOneKid) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: > actually I don't think CSS applies it since the style got applied during the for loop through DOM manipulation

Even though the element is created in the for loop, I think there is still a way to properly select and style it using CSS. The CSS styles should apply in any DOM state.

**Review by EthanThatOneKid — APPROVED** [review]
Thank you for modularizing and refactoring the `copy` function! This functionality was used in several places on the site, so it was a perfect candidate for such a refactor. Looks great!

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 6 above)
Comment (EthanThatOneKid) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: Daniel resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/629/commits/e8e104a4b920469abba97a437787121c17df6ac9>.

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 4 above)
Comment (EthanThatOneKid) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: Daniel resolved in <https://github.com/EthanThatOneKid/acmcsuf.com/pull/629/commits/e8e104a4b920469abba97a437787121c17df6ac9>.

File: src/routes/(site)/blog/[id]/blog-body.svelte [hunk 7]
```diff
@@ -3,38 +3,13 @@
...
       if (parentDiv) {
-        parentDiv!.style.position = 'relative';
+        parentDiv.classList.add('copy-code-parent');
       }
-      let copyBtn = document.createElement('button');
+      const copyBtn = document.createElement('button');
       copyBtn.classList.add('copy-code');
-      copyBtn.style.cssText =
-        'position: absolute; padding: 1rem; top: 1rem; right: 1rem; outline: none; background-color: transparent; border:none; cursor: pointer';
-      copyBtn.style.backgroundImage = 'url(data:image/svg+xml;utf8,' + svgCode + ')';
```
Comment (jaasonw) [inline src/routes/(site)/blog/[id]/blog-body.svelte:37]: possible to create image tag for this or no? make possible to change color with dark mode

File: src/lib/public/copy/copy.ts [hunk 8]
```diff
@@ -0,0 +1,9 @@
+import { toast, ToastType } from '$lib/components/toaster/toasts';
+
+/** @see <https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText> */
```
Comment (jaasonw) [inline src/lib/public/copy/copy.ts:3]: original documentation for this wasnt good, document the fact that this copies text to the clipboard and then displays a notification or error message

**Review by jaasonw — CHANGES_REQUESTED** [review]
also border is not work on blog notif

image

File: src/routes/(site)/events/event.svelte [hunk 9]
```diff
@@ -108,7 +99,7 @@
             info.acmPath.slug
           )}
       >
-        <CopyText />
+        <img src="/assets/svg/copy-text.svg" alt="copy text button" />
```
Comment (jaasonw) [inline src/routes/(site)/events/event.svelte]: copy button not respond to dark mode
image

**Review by jaasonw — CHANGES_REQUESTED** [review]

File: src/routes/(site)/events/event.svelte (hunk 9 above)
Comment (anhduy1202) [reply src/routes/(site)/events/event.svelte]: > copy button not respond to dark mode
> image

yeah I just realized that now, probably make an img element instead of using background-image

**Comment by anhduy1202** [comment]
# Update
- Toast pop-up border color now fixed ( I used acm-general color for the blog popup )
- Copy icon now change color depends on dark/light mode ( I can refactor the MutationObserver function into a new file if you want )

# Screenshots
Screen Shot 2022-10-28 at 12 30 06 PM

Screen Shot 2022-10-28 at 12 30 44 PM

# Remaining Issues:
Screen Shot 2022-10-28 at 12 32 43 PM

File: src/routes/(site)/events/event.svelte (hunk 9 above)
Comment (anhduy1202) [reply src/routes/(site)/events/event.svelte]: done

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 7 above)
Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/blog-body.svelte:37]: done

File: src/lib/public/copy/copy.ts (hunk 8 above)
Comment (anhduy1202) [reply src/lib/public/copy/copy.ts:3]: just added some comment to explain what this function do

File: src/routes/(site)/events/event.svelte [hunk 10]
```diff
@@ -29,6 +20,35 @@
...
+      copySvg.src = body?.classList.contains('light')
+        ? '/assets/svg/copy-text-dark.svg'
+        : '/assets/svg/copy-text-light.svg';
+    }
+    const options = {
+      attributes: true,
+    };
+
+    function callback(mutationList: Array<MutationRecord>) {
+      mutationList.forEach((mutation: any) => {
```
Comment (jaasonw) [inline src/routes/(site)/events/event.svelte]: remove this any

Comment (anhduy1202) [reply src/routes/(site)/events/event.svelte]: done in this [PR](https://github.com/EthanThatOneKid/acmcsuf.com/pull/629/commits/7497cb212b78689f075570e399b3c0c1eca3e257)

**Review by EthanThatOneKid — APPROVED** [review]
LGTM!

File: src/routes/(site)/blog/[id]/+page.svelte [hunk 11]
```diff
@@ -6,21 +6,16 @@
...
-  import { toast, ToastType } from '$lib/components/toaster/toasts';
+  import { copy } from '$lib/public/copy/copy';
   export let data: PageData;
   onMount(() => {
```
Comment (jaasonw) [inline src/routes/(site)/blog/[id]/+page.svelte]: what is this entire onmount block used for? look like dead code to me

File: src/routes/(site)/blog/[id]/blog-body.svelte [hunk 12]
```diff
@@ -1,41 +1,32 @@
...
-    for (let code of pre) {
-      let parentDiv = code.parentElement;
-      if (parentDiv) {
-        parentDiv!.style.position = 'relative';
-      }
-      let copyBtn = document.createElement('button');
+    const body = document.querySelector('body');
+    if (!body) return;
+
+    for (const codeblock of document.querySelectorAll('pre')) {
```
Comment (jaasonw) [inline src/routes/(site)/blog/[id]/blog-body.svelte]: codeblock need camelcase

**Review by jaasonw — CHANGES_REQUESTED** [review]

File: src/routes/(site)/blog/[id]/+page.svelte (hunk 11 above)
Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/+page.svelte]: yeah cause Ethan refactored it, removed now

File: src/routes/(site)/blog/[id]/blog-body.svelte (hunk 12 above)
Comment (anhduy1202) [reply src/routes/(site)/blog/[id]/blog-body.svelte]: done

**Review by jaasonw — APPROVED** [review]
