### PR TITLE
fix blog css when not javascript

### LINKED ISSUE #564: Blog: Failure to truncate previews without JS
### What happened?

Before the JavaScript is loaded on `/events`, the list of blog post previews is a list of entire blog posts. This is due to a failure in visually truncating the text without JavaScript.
image

### PR DESCRIPTION
**Pull request by jaasonw**
# changes
1. refactor blog entry into own component
2. refactor to use only vanilla css (scss doesnt seem to play nicely w/o js and i cbf to find out why)
3. make blog title a clickable link (for some reason a tags wouldnt properly render content inside of it without js, see screenshot)
image

# results

https://user-images.githubusercontent.com/8981287/193696654-080671f8-aa97-4aaa-bc9f-a46499d2edbc.mov

# known issues
see above screenshot, with js disabled the div is non clickable as the a tag does not properly render. work around for this was make the blog title clickable so non js users still have a way to click on the blog post

### CODE REVIEW

File: src/routes/blog/+page.svelte [hunk 1]
```diff
@@ -64,31 +58,7 @@
...
-                  calendar: 'gregory',
-                  year: 'numeric',
-                  month: 'long',
-                  day: 'numeric',
-                })} •
-              {readingTime(post.html)} min read
-              <Labels data={post.labels} {selectedLabels} />
-            </p>
-          </a>
+          <BlogEntry {post} {selectedLabels} />
```
Comment (EthanThatOneKid) [inline src/routes/blog/+page.svelte]: Nit:
```suggestion
          <BlogPostPreview {post} {selectedLabels} />
```

File: src/lib/components/blog/blog-entry.svelte [hunk 2]
```diff
@@ -0,0 +1,87 @@
+<script lang="ts">
+  import { makeBlogPostPageUrl } from '$lib/public/blog/urls';
+  import { readingTime } from '$lib/public/blog/utils';
+  import { Temporal } from '@js-temporal/polyfill';
+  import Labels from '../../../routes/blog/labels.svelte';
+
+  export let post: any;
```
Comment (EthanThatOneKid) [inline src/lib/components/blog/blog-entry.svelte]: The BlogPost type definition is exported from `src/lib/public/blog/types.ts` and should be used as the type for the variable `post`.

File: src/lib/components/blog/blog-entry.svelte [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+  export let selectedLabels: any;
```
Comment (EthanThatOneKid) [inline src/lib/components/blog/blog-entry.svelte]: Declare `selectedLabels` using the correct type.

File: src/lib/components/blog/blog-entry.svelte [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+  console.log(post);
```
Comment (EthanThatOneKid) [inline src/lib/components/blog/blog-entry.svelte]: Nit: Rogue console log.

File: src/lib/components/blog/blog-entry.svelte [hunk 5]
```diff
@@ -0,0 +1,87 @@
+<script lang="ts">
+  import { makeBlogPostPageUrl } from '$lib/public/blog/urls';
+  import { readingTime } from '$lib/public/blog/utils';
+  import { Temporal } from '@js-temporal/polyfill';
+  import Labels from '../../../routes/blog/labels.svelte';
```
Comment (EthanThatOneKid) [inline src/lib/components/blog/blog-entry.svelte]: As you can see, since Labels is under the `/routes/` directory, you get this unwanted relative path with lots of `../`s. Since the BlogPostPreview component is only expected to be used on the `/blog` page endpoint, it might make sense for the location of this file to be adjacent to the Labels component file.

File: src/lib/components/blog/blog-entry.svelte [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+      <Labels data={post.labels} {selectedLabels} />
+    </p>
+  </a>
+</div>
+
+<style>
+  .post {
+    padding: 2em;
+  }
+  a {
```
Comment (EthanThatOneKid) [inline src/lib/components/blog/blog-entry.svelte]: Nit: Space out CSS blocks. 
Note: Where to put empty lines in this repository should be covered in our style guidelines if not already.

**Review by EthanThatOneKid — COMMENTED** [review]
Thanks for taking the extra effort to refactor the blog post preview component on top of resolving the targeted bug. I reviewed your refactor and left a few comments.

File: src/lib/components/blog/blog-entry.svelte (hunk 2 above)
Comment (jaasonw) [reply src/lib/components/blog/blog-entry.svelte]: addressed

File: src/lib/components/blog/blog-entry.svelte (hunk 3 above)
Comment (jaasonw) [reply src/lib/components/blog/blog-entry.svelte]: addressed

File: src/lib/components/blog/blog-entry.svelte (hunk 4 above)
Comment (jaasonw) [reply src/lib/components/blog/blog-entry.svelte]: addressed

File: src/lib/components/blog/blog-entry.svelte (hunk 5 above)
Comment (jaasonw) [reply src/lib/components/blog/blog-entry.svelte]: addressed

File: src/lib/components/blog/blog-entry.svelte (hunk 6 above)
Comment (jaasonw) [reply src/lib/components/blog/blog-entry.svelte]: addressed

File: src/routes/blog/+page.svelte (hunk 1 above)
Comment (jaasonw) [reply src/routes/blog/+page.svelte]: addressed

**Review by EthanThatOneKid — APPROVED** [review]
