### PR TITLE
Fix for website-issue-183

### LINKED ISSUE #183: Strip unwanted backslashes from event titles
### What happened?

When certain characters are included in the event title on Google Calendar (such as commas), a backslash is awkwardly placed as well. To solve this, we can remove all of the backslashes from the title on the backend.

weird-commas

### PR DESCRIPTION
**Pull request by janiljohn**
Added a function called cleanSummary to common.ts which receives a string called summary. The .replace() function is called on summary to replace any \ with an empty string. This function is then exported and used in the parse.ts file.

### CODE REVIEW

File: src/lib/ical/common.ts [hunk 1]
```diff
@@ -130,3 +130,10 @@ export const sortByDate = () => {
 export const filterIfPassed = (now: number, offset: number = 0) => {
 	return ({ date }: { date: Date }) => date.valueOf() + offset > now;
 };
+
+
+export const cleanSummary = (summary?: string) => {
+  if(summary === undefined)
+		return "Unnamed Event";
```
Comment (EthanThatOneKid) [inline src/lib/ical/common.ts]: To conform with our style guidelines, I propose we format the code like so:

```suggestion
  if (summary === undefined) return "Unnamed Event";

```

**Review by EthanThatOneKid — CHANGES_REQUESTED** [review]
Well done! I had a minor nitpick on line 136, but I am comfortable merging once that is resolved. Thanks for the contribution, @janiljohn!

File: src/lib/ical/common.ts (hunk 1 above)
Comment (janiljohn) [reply src/lib/ical/common.ts]: Ah I see. Sounds good to me.
