### PR TITLE
fix inconsistent variable name (Url)

### LINKED ISSUE #817: Inconsistent variable name `Url`
### What happened?

It can be tricky deciding which way to capitalize a variable name. Let's make it not so tricky by deciding that from this point, all camel case variable names containing acronyms should always be fully capitalized unless it is the first segment of the camel case variable name.

For example:

**OK** | **NOT OK**
---|---
`getURL` | `getUrl`
`urlFrom` | `UrlFrom`

Related:
- [`fa28791` (Comment)](https://github.com/EthanThatOneKid/acmcsuf.com/commit/fa28791369259bc370e866210a3aef1061a7030b#r105160756)

### PR DESCRIPTION
**Pull request by Louiza02**
Fixes issue #817

### CODE REVIEW

File: src/lib/server/blog/gql.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ export function gql(ghDiscussionCategoryId: string) {
           author {
             login
             url
-            avatarUrl
+            avatarURL
```
Comment (EthanThatOneKid) [inline src/lib/server/blog/gql.ts]: Since the GitHub GraphQL API does not abide by the same standards as we do, it uses the alternative spelling which must be respected in the GraphQL query and the eventual GraphQL response. 
```suggestion
            avatarUrl
```

File: src/lib/server/certificates/gql.test.ts [hunk 2]
```diff
@@ -55,7 +55,7 @@ test('makeReleasesQuery', () => {
   user(login: "USERNAME") {
     name
     bioHTML
-    avatarUrl
+    avatarURL
```
Comment (EthanThatOneKid) [inline src/lib/server/certificates/gql.test.ts]: Follow-up:
```suggestion
    avatarUrl
```

File: src/lib/server/certificates/gql.ts [hunk 3]
```diff
@@ -30,7 +30,7 @@ export function makeReleasesQuery(q: RepoQuery): string {
   user(login: "${q.username}") {
     name
     bioHTML
-    avatarUrl
+    avatarURL
```
Comment (EthanThatOneKid) [inline src/lib/server/certificates/gql.ts]: Follow-up:
```suggestion
    avatarUrl
```

File: src/lib/server/blog/posts.ts [hunk 4]
```diff
@@ -78,30 +78,30 @@ function cacheBlogPosts(output: any): BlogPost[] {
...
 
     const url = `/blog/${id}`;
     const officer = getOfficerByGhUsername(author.login);
-    const authorUrl = author.url;
+    const authorURL = author.url;
     const displayname = author.login;
     const fullname = officer?.fullName;
     const picture: string =
-      author.avatarUrl ?? `/assets/authors/${officer?.picture || 'placeholder.webp'}`;
+      author.avatarURL ?? `/assets/authors/${officer?.picture || 'placeholder.webp'}`;
```
Comment (EthanThatOneKid) [inline src/lib/server/blog/posts.ts]: Follow-up:
```suggestion
      author.avatarUrl ?? `/assets/authors/${officer?.picture || 'placeholder.webp'}`;
```

**Review by EthanThatOneKid — CHANGES_REQUESTED** [review]
This looks great so far!

There is one case where the change should not be applied, so I left a few comments to explain that one case.

**Comment by Louiza02** [comment]
Hi @EthanThatOneKid, 
I'm sorry I didn't know, I understand now, fixed it in my last commits.

**Review by EthanThatOneKid — CHANGES_REQUESTED** [review]
All good @Louiza02! Nice work!

One more thing: Our workflow caught some errors regarding import statements which happen to import the functions that we have changed. Run `npm run check` to see a list of these errors. Please resolve all of these name changes.

**Review by EthanThatOneKid — CHANGES_REQUESTED** [review]
@Louiza02, please run `npm run format` to resolve any formatting errors in your branch.

**Review by EthanThatOneKid — APPROVED** [review]
Congratulations, @Louiza02! Thank you for your work on this contribution. I will go ahead and merge this PR 😎

**Comment by EthanThatOneKid** [comment]
Resolves #817.
